services:
  - type: web
    name: text-similarity-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
